version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: kicksense_db
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: kicksense
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/home/postgres/pgdata/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: always

volumes:
  timescaledb_data: